Resources:
  vpc:
    Type: AWS::EC2::VPC
    Properties:
      CidrBlock: 10.0.0.0/16
      Tags:
        - Key: Name
          Value: divide-production-vpc
    Metadata:
      aws:cdk:path: BaseStack/vpc
  subnetpublic1a:
    Type: AWS::EC2::Subnet
    Properties:
      AvailabilityZone: ap-northeast-1a
      CidrBlock: 10.0.11.0/24
      Tags:
        - Key: Name
          Value: divide-production-subnet-public-1a
      VpcId:
        Ref: vpc
    Metadata:
      aws:cdk:path: BaseStack/subnet-public-1a
  subnetpublic1c:
    Type: AWS::EC2::Subnet
    Properties:
      AvailabilityZone: ap-northeast-1c
      CidrBlock: 10.0.12.0/24
      Tags:
        - Key: Name
          Value: divide-production-subnet-public-1c
      VpcId:
        Ref: vpc
    Metadata:
      aws:cdk:path: BaseStack/subnet-public-1c
  subnetapp1a:
    Type: AWS::EC2::Subnet
    Properties:
      AvailabilityZone: ap-northeast-1a
      CidrBlock: 10.0.21.0/24
      Tags:
        - Key: Name
          Value: divide-production-subnet-app-1a
      VpcId:
        Ref: vpc
    Metadata:
      aws:cdk:path: BaseStack/subnet-app-1a
  subnetapp1c:
    Type: AWS::EC2::Subnet
    Properties:
      AvailabilityZone: ap-northeast-1c
      CidrBlock: 10.0.22.0/24
      Tags:
        - Key: Name
          Value: divide-production-subnet-app-1c
      VpcId:
        Ref: vpc
    Metadata:
      aws:cdk:path: BaseStack/subnet-app-1c
  subnetprivate1a:
    Type: AWS::EC2::Subnet
    Properties:
      AvailabilityZone: ap-northeast-1a
      CidrBlock: 10.0.31.0/24
      Tags:
        - Key: Name
          Value: divide-production-subnet-private-1a
      VpcId:
        Ref: vpc
    Metadata:
      aws:cdk:path: BaseStack/subnet-private-1a
  subnetprivate1c:
    Type: AWS::EC2::Subnet
    Properties:
      AvailabilityZone: ap-northeast-1c
      CidrBlock: 10.0.32.0/24
      Tags:
        - Key: Name
          Value: divide-production-subnet-private-1c
      VpcId:
        Ref: vpc
    Metadata:
      aws:cdk:path: BaseStack/subnet-private-1c
  igw:
    Type: AWS::EC2::InternetGateway
    Properties:
      Tags:
        - Key: Name
          Value: divide-production-igw
    Metadata:
      aws:cdk:path: BaseStack/igw
  vpcgatewayattachment:
    Type: AWS::EC2::VPCGatewayAttachment
    Properties:
      InternetGatewayId:
        Ref: igw
      VpcId:
        Ref: vpc
    Metadata:
      aws:cdk:path: BaseStack/vpc-gateway-attachment
  divideproductionroutetablepublic:
    Type: AWS::EC2::RouteTable
    Properties:
      Tags:
        - Key: Name
          Value: divide-production-route-table-public
      VpcId:
        Ref: vpc
    Metadata:
      aws:cdk:path: BaseStack/divide-production-route-table-public
  divideproductionroutetablepublicpublicroute:
    Type: AWS::EC2::Route
    Properties:
      DestinationCidrBlock: 0.0.0.0/0
      GatewayId:
        Ref: igw
      RouteTableId:
        Ref: divideproductionroutetablepublic
    Metadata:
      aws:cdk:path: BaseStack/divide-production-route-table-public-public-route
  divideproductionsubnetpublic1aroutetableassociation:
    Type: AWS::EC2::SubnetRouteTableAssociation
    Properties:
      RouteTableId:
        Ref: divideproductionroutetablepublic
      SubnetId:
        Ref: subnetpublic1a
    Metadata:
      aws:cdk:path: BaseStack/divide-production-subnet-public-1a-route-table-association
  divideproductionsubnetpublic1croutetableassociation:
    Type: AWS::EC2::SubnetRouteTableAssociation
    Properties:
      RouteTableId:
        Ref: divideproductionroutetablepublic
      SubnetId:
        Ref: subnetpublic1c
    Metadata:
      aws:cdk:path: BaseStack/divide-production-subnet-public-1c-route-table-association
  divideproductionroutetableapp:
    Type: AWS::EC2::RouteTable
    Properties:
      Tags:
        - Key: Name
          Value: divide-production-route-table-app
      VpcId:
        Ref: vpc
    Metadata:
      aws:cdk:path: BaseStack/divide-production-route-table-app
  divideproductionsubnetapp1aroutetableassociation:
    Type: AWS::EC2::SubnetRouteTableAssociation
    Properties:
      RouteTableId:
        Ref: divideproductionroutetableapp
      SubnetId:
        Ref: subnetapp1a
    Metadata:
      aws:cdk:path: BaseStack/divide-production-subnet-app-1a-route-table-association
  divideproductionsubnetapp1croutetableassociation:
    Type: AWS::EC2::SubnetRouteTableAssociation
    Properties:
      RouteTableId:
        Ref: divideproductionroutetableapp
      SubnetId:
        Ref: subnetapp1c
    Metadata:
      aws:cdk:path: BaseStack/divide-production-subnet-app-1c-route-table-association
  divideproductionroutetableprivate:
    Type: AWS::EC2::RouteTable
    Properties:
      Tags:
        - Key: Name
          Value: divide-production-route-table-private
      VpcId:
        Ref: vpc
    Metadata:
      aws:cdk:path: BaseStack/divide-production-route-table-private
  divideproductionsubnetprivate1aroutetableassociation:
    Type: AWS::EC2::SubnetRouteTableAssociation
    Properties:
      RouteTableId:
        Ref: divideproductionroutetableprivate
      SubnetId:
        Ref: subnetprivate1a
    Metadata:
      aws:cdk:path: BaseStack/divide-production-subnet-private-1a-route-table-association
  divideproductionsubnetprivate1croutetableassociation:
    Type: AWS::EC2::SubnetRouteTableAssociation
    Properties:
      RouteTableId:
        Ref: divideproductionroutetableprivate
      SubnetId:
        Ref: subnetprivate1c
    Metadata:
      aws:cdk:path: BaseStack/divide-production-subnet-private-1c-route-table-association
  divideproductionnetworkaclpublic:
    Type: AWS::EC2::NetworkAcl
    Properties:
      Tags:
        - Key: Name
          Value: divide-production-network-acl-public
      VpcId:
        Ref: vpc
    Metadata:
      aws:cdk:path: BaseStack/divide-production-network-acl-public
  divideproductionnetworkaclpublicouboundentry:
    Type: AWS::EC2::NetworkAclEntry
    Properties:
      CidrBlock: 0.0.0.0/0
      Egress: true
      NetworkAclId:
        Ref: divideproductionnetworkaclpublic
      Protocol: -1
      RuleAction: allow
      RuleNumber: 100
    Metadata:
      aws:cdk:path: BaseStack/divide-production-network-acl-public-oubound-entry
  divideproductionnetworkaclpublicinboundentry:
    Type: AWS::EC2::NetworkAclEntry
    Properties:
      CidrBlock: 0.0.0.0/0
      Egress: false
      NetworkAclId:
        Ref: divideproductionnetworkaclpublic
      Protocol: -1
      RuleAction: allow
      RuleNumber: 100
    Metadata:
      aws:cdk:path: BaseStack/divide-production-network-acl-public-inbound-entry
  networkaclassosiationpublicsubnet1a:
    Type: AWS::EC2::SubnetNetworkAclAssociation
    Properties:
      NetworkAclId:
        Ref: divideproductionnetworkaclpublic
      SubnetId:
        Ref: subnetpublic1a
    Metadata:
      aws:cdk:path: BaseStack/network-acl-assosiation-public-subnet-1a
  networkaclassosiationpublicsubnet1c:
    Type: AWS::EC2::SubnetNetworkAclAssociation
    Properties:
      NetworkAclId:
        Ref: divideproductionnetworkaclpublic
      SubnetId:
        Ref: subnetpublic1c
    Metadata:
      aws:cdk:path: BaseStack/network-acl-assosiation-public-subnet-1c
  divideproductionnetworkaclapp:
    Type: AWS::EC2::NetworkAcl
    Properties:
      Tags:
        - Key: Name
          Value: divide-production-network-acl-app
      VpcId:
        Ref: vpc
    Metadata:
      aws:cdk:path: BaseStack/divide-production-network-acl-app
  divideproductionnetworkaclappouboundentry:
    Type: AWS::EC2::NetworkAclEntry
    Properties:
      CidrBlock: 0.0.0.0/0
      Egress: true
      NetworkAclId:
        Ref: divideproductionnetworkaclapp
      Protocol: -1
      RuleAction: allow
      RuleNumber: 100
    Metadata:
      aws:cdk:path: BaseStack/divide-production-network-acl-app-oubound-entry
  divideproductionnetworkaclappinboundentry:
    Type: AWS::EC2::NetworkAclEntry
    Properties:
      CidrBlock: 0.0.0.0/0
      Egress: false
      NetworkAclId:
        Ref: divideproductionnetworkaclapp
      Protocol: -1
      RuleAction: allow
      RuleNumber: 100
    Metadata:
      aws:cdk:path: BaseStack/divide-production-network-acl-app-inbound-entry
  networkaclassosiationappsubnet1a:
    Type: AWS::EC2::SubnetNetworkAclAssociation
    Properties:
      NetworkAclId:
        Ref: divideproductionnetworkaclapp
      SubnetId:
        Ref: subnetapp1a
    Metadata:
      aws:cdk:path: BaseStack/network-acl-assosiation-app-subnet-1a
  networkaclassosiationappsubnet1c:
    Type: AWS::EC2::SubnetNetworkAclAssociation
    Properties:
      NetworkAclId:
        Ref: divideproductionnetworkaclapp
      SubnetId:
        Ref: subnetapp1c
    Metadata:
      aws:cdk:path: BaseStack/network-acl-assosiation-app-subnet-1c
  divideproductionnetworkaclprivate:
    Type: AWS::EC2::NetworkAcl
    Properties:
      Tags:
        - Key: Name
          Value: divide-production-network-acl-private
      VpcId:
        Ref: vpc
    Metadata:
      aws:cdk:path: BaseStack/divide-production-network-acl-private
  divideproductionnetworkaclprivateouboundentry:
    Type: AWS::EC2::NetworkAclEntry
    Properties:
      CidrBlock: 0.0.0.0/0
      Egress: true
      NetworkAclId:
        Ref: divideproductionnetworkaclprivate
      Protocol: -1
      RuleAction: allow
      RuleNumber: 100
    Metadata:
      aws:cdk:path: BaseStack/divide-production-network-acl-private-oubound-entry
  divideproductionnetworkaclprivateinboundentry:
    Type: AWS::EC2::NetworkAclEntry
    Properties:
      CidrBlock: 0.0.0.0/0
      Egress: false
      NetworkAclId:
        Ref: divideproductionnetworkaclprivate
      Protocol: -1
      RuleAction: allow
      RuleNumber: 100
    Metadata:
      aws:cdk:path: BaseStack/divide-production-network-acl-private-inbound-entry
  networkaclassosiationprivatesubnet1a:
    Type: AWS::EC2::SubnetNetworkAclAssociation
    Properties:
      NetworkAclId:
        Ref: divideproductionnetworkaclprivate
      SubnetId:
        Ref: subnetprivate1a
    Metadata:
      aws:cdk:path: BaseStack/network-acl-assosiation-private-subnet-1a
  networkaclassosiationprivatesubnet1c:
    Type: AWS::EC2::SubnetNetworkAclAssociation
    Properties:
      NetworkAclId:
        Ref: divideproductionnetworkaclprivate
      SubnetId:
        Ref: subnetprivate1c
    Metadata:
      aws:cdk:path: BaseStack/network-acl-assosiation-private-subnet-1c
Parameters:
  BootstrapVersion:
    Type: AWS::SSM::Parameter::Value<String>
    Default: /cdk-bootstrap/hnb659fds/version
    Description: Version of the CDK Bootstrap resources in this environment, automatically retrieved from SSM Parameter Store. [cdk:skip]
Rules:
  CheckBootstrapVersion:
    Assertions:
      - Assert:
          Fn::Not:
            - Fn::Contains:
                - - "1"
                  - "2"
                  - "3"
                  - "4"
                  - "5"
                - Ref: BootstrapVersion
        AssertDescription: CDK bootstrap stack version 6 required. Please run 'cdk bootstrap' with a recent version of the CDK CLI.

