services:
  backend:
    build:
      context: .
      dockerfile: ./Dockerfile
    init: true
    environment:
      - TZ=Asia/Tokyo
    command: sleep infinity
    volumes:
      - ../../.:/current
      - server-node-modules:/current/server/node_modules
volumes:
  server-node-modules: