services:
  cdk-container:
    build:
      context: .
      dockerfile: ./Dockerfile
    init: true
    environment:
      - TZ=Asia/Tokyo
    command: sleep infinity
    volumes:
      - type: bind
        source: '../../.'
        target: '/current'
      - type: bind
        source: '~/.aws'
        target: '/root/.aws'
        read_only: true
      - type: volume
        source: cdk-node-modules
        target: '/current/node_modules'
volumes:
  cdk-node-modules: