services:
  container:
    build:
      context: .
      dockerfile: ./Dockerfile
    init: true
    environment:
      - TZ=Asia/Tokyo
    command: sleep infinity
    volumes:
      - ../../.:/current
      - nextjs-node-modules:/current/nextjs/node_modules
volumes:
  nextjs-node-modules: